version: '3.8'

services:
  foyer-app:
    image: omarchouikh/foyer-app-repo:${TAG:-latest}
    container_name: foyer-app
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_PORT=8086
      - SERVER_SERVLET_CONTEXT_PATH=/Foyer
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/Foyer/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-foyer}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password="]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
